### ISSUE TITLE
HTTP Status 500 - No WebApplicationContext found

### ISSUE THREAD

**Issue by EMCP** [olivergierke/spring-restbucks#13]
Edit : It's not clear in the readme how to modify this project to deploy it to a servlet container like Tomcat... 
It would be great to outline how to run it in the readme with mvn jetty:run and what to modify if serving it in a container like Tomcat.

When I deploy the project with a blank web.xml manually added to the war I get this : 

HTTP Status 500 - No WebApplicationContext found: no ContextLoaderListener registered?

type Exception report

message No WebApplicationContext found: no ContextLoaderListener registered?

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener registered?
	org.springframework.web.context.support.WebApplicationContextUtils.getRequiredWebApplicationContext(WebApplicationContextUtils.java:90)
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.lookupEntityManagerFactory(OpenEntityManagerInViewFilter.java:216)
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.lookupEntityManagerFactory(OpenEntityManagerInViewFilter.java:203)
	org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:148)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108)

**Comment by otrosien** [comment]
close - It's a spring boot application nowadays. (see #61)
