### ISSUE TITLE
Error: Unable to access jarfile target/*.war

### ISSUE THREAD

**Issue by Stefan-Isele** [olivergierke/spring-restbucks#21]
Hi, when I enter the command 
java -jar target/*.war  as described in the read.me 
I get :
Error: Unable to access jarfile target/*.war

on Windows 7,

**Comment by olivergierke** [comment]
Whatever Windows needs to actually execute this. There's a WAR in the target folder, that's an executable (currently named `restbucks-1.0.0.BUILD-SNAPSHOT.war` but that might change) one you run with `java -jar $pathToTheExecutable`.
