### ISSUE TITLE
mvn clean package not working !

### ISSUE THREAD

**Issue by bismoy2013** [olivergierke/spring-restbucks#25]
Don't know why but errors are showing up after running mvn clean package on terminal .

**Comment by olivergierke** [comment]
Can you still reproduce the issue?

**Comment by ikolomiets** [comment]
Cloned from master - it builds, tests and runs ok now! But when I navigate to http://localhost:8080/browser/index.html (as per README "Quickstart") it returns "500 Internal Server Error" without any output to console on the server side :(

**Comment by olivergierke** [comment]
That works for me:
![bildschirmfoto 2015-05-20 um 17 42 21](https://cloud.githubusercontent.com/assets/128577/7729927/a4d2aaea-ff17-11e4-9729-a2b9ec976b5a.PNG)

Anyway, we probably should move to the Spring Data REST provided HAL browser anyway. Created #35 to take care of that.

**Comment by ikolomiets** [comment]
It works now.

**Comment by olivergierke** [comment]
\o/ :smile:

**Comment by bismoy2013** [comment]
Oops sorry :) forgot to keep track of this issue :(
