### ISSUE TITLE
Trying this repository with MySQL as database service

### ISSUE THREAD

**Issue by jimishparekh** [olivergierke/spring-restbucks#26]
Hey @olivergierke ,
I am trying to configure MySQL database with this repository. To do that I have tried some things mentioned below:
pom.xml:

          <dependency>
	        <groupId>mysql</groupId>
	        <artifactId>mysql-connector-java</artifactId>
	    </dependency>
and In application.properties: 
spring.jpa.generate-ddl=true

server.port=8080

dialect=org.hibernate.dialect.MySQL5InnoDBDialect

spring.datasource.url=jdbc:mysql://localhost/restBucks

spring.datasource.driverClassName=com.mysql.jdbc.Driver

spring.datasource.username=root

spring.datasource.password=root

but I am facing about 15 errors with title of "beanCreationException". you can see my post on stackoverflow at:
http://stackoverflow.com/questions/25930191/connect-mysql-to-spring-application

can you please suggest/guide me how to achieve this?
Thanks

**Comment by olivergierke** [comment]
Closing this, as it's more of a question than something to fix in this project.
