### ISSUE TITLE
build failing due to non existing version for artificatId  spring-data-releasetrain

### ISSUE THREAD

**Issue by alanmehio** [olivergierke/spring-restbucks#28]
<spring-data-releasetrain.version>Fowler-BUILD-SNAPSHOT</spring-data-releasetrain.version>

not found . I replaced it with Dijkstra-SR4 and I get complilation error

**Comment by olivergierke** [comment]
That's actually been [in place since June 2014 already](https://github.com/olivergierke/spring-restbucks/blame/46b4d039ec7d7b88e7bd9d37672a24afeb8a967e/pom.xml#L94)? Anyway, should be working now.
