### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by zachariahyoung** [olivergierke/spring-restbucks#30]
Oliver,

I would like to know if you would be open to the idea of setting this project up to do am Automated Build on Docker Hub.

http://docs.docker.com/docker-hub/builds/

This is an example I hacked together.  
https://registry.hub.docker.com/u/zachariahyoung/docker-rest/

Thanks
Zach

**Comment by olivergierke** [comment]
That's a great idea, Zach! I haven't had any too detailed exposure to Docker yet, but would be happy to see a pull request that adds the Docker file and instructions how to run a container with the app in the README. Wanna give it a shot?

**Comment by otrosien** [comment]
see https://github.com/olivergierke/spring-restbucks/pull/62

**Comment by otrosien** [comment]
.. can be closed
