### ISSUE TITLE
Documentation is broken for engine, pages

### ISSUE THREAD

**Issue by pimlottc** [olivergierke/spring-restbucks#32]
Following the expanded CURIEs for `restbucks:engine` and `restbucks:pages` gives a `HTTP 500` response.

> GET http://localhost:8080/alps/engine 500 (Internal Server Error)
> GET http://localhost:8080/alps/pages 500 (Internal Server Error)

There is no output on the console from these requests.

**Comment by olivergierke** [comment]
I've filed a [ticket](https://jira.spring.io/browse/DATAREST-552) in Spring Data REST for that.
