### ISSUE TITLE
Race condition on executing tests

### ISSUE THREAD

**Issue by kosch** [olivergierke/spring-restbucks#40]
When running tests in this order:
-Dtest=OrderRepositoryIntegrationTest,ApplicationIntegrationTest,CreditCardRepositoryIntegrationTest 

I get an error:
CreditCardRepositoryIntegrationTest.createsCreditCard:41 » InvalidDataAccessResourceUsage

Cause is a JPA resource which is not cleaned up after OrderRepositoryIntegrationTest.
As workaround I added
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
to the OrderRepositoryIntegrationTest, but I'm sure you'll find a better solution for that :-)

Here is the test run output:
http://paste.scsys.co.uk/498717 

Executed with:
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /home/tf/ENV/apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-61-generic", arch: "amd64", family: "unix"

**Comment by thackel** [comment]
For me not even the normal `mvn clean test` is working:
```java
Tests in error: 
  CreditCardRepositoryIntegrationTest.createsCreditCard:41 » InvalidDataAccessResourceUsage
  PaymentRepositoryIntegrationTest.savesCreditCardPayment:45 » InvalidDataAccessResourceUsage
  PaymentServiceIntegrationTest.marksOrderAsPaid:46 » InvalidDataAccessResourceUsage
  PaymentServiceIntegrationTest.marksOrderAsTakenIfReceiptIsTaken:57 » InvalidDataAccessResourceUsage
  PaymentProcessIntegrationTest.cancelOrderBeforePayment:105->createNewOrder:146 » NestedServlet
  PaymentProcessIntegrationTest.processExistingOrder:72->discoverOrdersResource:169 » NestedServlet
  PaymentProcessIntegrationTest.processNewOrder:89->createNewOrder:146 » NestedServlet
```

But the solution @kosch provided above "fixes" the problem and all tests are fine.

```bash
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /home/thackel/java/apache-maven-3.3.3
Java version: 1.8.0_60, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-28-generic", arch: "amd64", family: "unix"
```

**Comment by kosch** [comment]
Different behaviour on different systems, depends on how the resources are cleaned up, maybe GC runs later in our cases :-)

**Comment by otrosien** [comment]
This is going to be fixed with pull #48

**Comment by olivergierke** [comment]
Can you guys still reproduce this without any fixes applied? I think the culprit was a test case that manually bootstrapped an ApplicationContext, shut it down and by that also shut down the embedded database instance that's unique per JVM.

I removed that test a while ago, so I am wondering whether we still need to fix that. Adding `@DirtiesContext` everywhere is usually not a good idea as it significantly slows down the tests and the transactional nature of them should actually provide enough isloation.

**Comment by otrosien** [comment]
I'll try running the tests again, and report the findings.

**Comment by otrosien** [comment]
:+1: [INFO] BUILD SUCCESS

**Comment by thackel** [comment]
Execution of the given tests and the whole test suite are terminating successfully.
