### ISSUE TITLE
POSTing of new order fails

### ISSUE THREAD

**Issue by dschulten** [olivergierke/spring-restbucks#43]
With the current snapshot I cannot post new orders. In the HAL Browser all fields are disabled and show a red warning sign when hovering over them.
When posting this manually:

    {
    "lineItems": [
        {
            "quantity": 1,
            "size": "Gross",
            "price": "EUR 2.80",
            "name": "Cappuccino",
            "milk": "Vollmilch"
        }
    ],
    "price": "",
    "location": "Zum mitnehmen",
    "orderedDate": "",
    "status": "Zu zahlen"
    }

I get:

    {
    "cause": {
        "cause": {
            "cause": null,
            "message": "Argument #0 of constructor [constructor for org.springsource.restbucks.order.Order, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator"
        },
        "message": "Argument #0 of constructor [constructor for org.springsource.restbucks.order.Order, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator"
    },
    "message": "Could not read document: Argument #0 of constructor [constructor for org.springsource.restbucks.order.Order, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Argument #0 of constructor [constructor for org.springsource.restbucks.order.Order, annotations: {interface com.fasterxml.jackson.annotation.JsonCreator=@com.fasterxml.jackson.annotation.JsonCreator(mode=DEFAULT)}] has no property name annotation; must have name when multiple-parameter constructor annotated as Creator"
    }

**Comment by dschulten** [comment]
The root cause seems to be that sometimes constructor argument names are lost in my compilation, but not always (!)
Whenever reflection turns up "arg0, arg1" I get the above error. With "lineItems, location" it works.

**Comment by aycanadalwork** [comment]
I am getting the same on Intellij. Any suggestions?
